### ISSUE TITLE
事前テスト

### ISSUE THREAD

**Issue by IotaTech-Info** [IotaTech-Info/IotaJava_G4#1]
# 質問票
[事前テスト_JAVAG3.docx](https://github.com/ebforlearng1java/EBPro_G2/files/7669265/_JAVAG2.docx)

# 回答期限
10/14まで

# 提出形式
・解答を上記ファイルに記入すること
・ファイル名を「事前テスト_JAVAG4_自分名前.docx」に変更すること
・該当Issuesにアップすること

**Comment by JunyuChenJe** [comment]
[事前テスト_JAVAG4_陳俊宇.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9724928/_JAVAG4_.pdf)

**Comment by DDG-Edgerunners** [comment]
[事前テスト_JAVAG4_周靖陽.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9730417/_JAVAG4_.pdf)

**Comment by EB-Zengwenjie** [comment]
[事前テスト_JAVAG2_曾文傑.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9732396/_JAVAG2_.pdf)

**Comment by nakishigure** [comment]
[事前テスト_JAVAG4_陈思宏.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9738697/_JAVAG4_.pdf)

**Comment by DYLism** [comment]
[事前テスト_JAVAG4_戴玉霖.docx.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9739126/_JAVAG4_.docx.pdf)

**Comment by DYLism** [comment]
[事前テスト_JAVAG4_戴玉霖.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9739128/_JAVAG4_.pdf)

**Comment by hayleyqinn** [comment]
[事前テスト_JAVAG4_覃紅.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9739517/_JAVAG4_.pdf)

**Comment by chou-ikuyou** [comment]
[事前テスト_JAVAG4_張毓蓉.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9741856/_JAVAG4_.pdf)

**Comment by see3rd** [comment]
[事前テスト_JAVAG4_熊文倩.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9742366/_JAVAG4_.pdf)

**Comment by mazhiqiang26** [comment]
[事前テスト_JAVAG4_馬志強.docx](https://github.com/IotaTech-Info/IotaJava_G4/files/9742433/_JAVAG4_.docx)

**Comment by SuperDolly** [comment]
[事前テスト_JAVAG4_吴雨航.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9746455/_JAVAG4_.pdf)

**Comment by Knight-for-destiny** [comment]
[事前テスト_JAVAG4_宋澤宇.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9750870/_JAVAG4_.pdf)

**Comment by liuxiaoyang98** [comment]
[_JAVAG4_刘晓阳.docx](https://github.com/IotaTech-Info/IotaJava_G4/files/9763220/_JAVAG4_.docx)

**Comment by liuxiaoyang98** [comment]
[事前テスト_JAVAG4_刘晓阳.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9763231/_JAVAG4_.pdf)

**Comment by wangheng19941219** [comment]
[](url)
[事前テスト_JAVAG4_王恒.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9765512/_JAVAG4_.pdf)

**Comment by wangsy100** [comment]
[事前テスト_JAVAG4_王舒瑜.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9767022/_JAVAG4_.pdf)

**Comment by xylh1116** [comment]
[事前テスト_JAVAG4_薛岩.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9769826/_JAVAG4_.pdf)

**Comment by daisylushadow** [comment]
[事前テスト_JAVAG4_陸鈺文　.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9770007/_JAVAG4_.pdf)

**Comment by WilliamLawTC** [comment]
[事前テスト＿JAVAＧ4＿羅天馳.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9770869/JAVA.4.pdf)

**Comment by yuki00001** [comment]
[事前テスト_JAVAG4_文迦.docx](https://github.com/IotaTech-Info/IotaJava_G4/files/9771250/_JAVAG4_.docx)

**Comment by cuiguangpuxiu** [comment]
[事前テスト_JAVAG4_崔光普秀.docx](https://github.com/IotaTech-Info/IotaJava_G4/files/9771526/_JAVAG4_.docx)

**Comment by DYswag** [comment]
[事前テスト_JAVAG4_段沢偉.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9775639/_JAVAG4_.pdf)

**Comment by Hitsune369** [comment]
[事前テスト_JAVAG4_李必恒.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9776601/_JAVAG4_.pdf)

**Comment by KakuShunryo** [comment]
[事前テスト_JAVAG2_郭俊良.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9776881/_JAVAG2_.pdf)

**Comment by 21q2106** [comment]
[事前test_JAVAG4_李融融.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9777985/test_JAVAG4_.pdf)

**Comment by 21q2106** [comment]
[事前テスト_JAVAG4_李融融.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9777995/_JAVAG4_.pdf)

**Comment by Haruka0204** [comment]
[事前テスト_JAVAG4_王少筠.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9778601/_JAVAG4_.pdf)

**Comment by donghe0216** [comment]
[事前テスト_JAVAG4_董赫.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9782075/_JAVAG4_.pdf)

**Comment by jyiiki** [comment]
[事前テスト_JAVAG4_jiyi.pdf](https://github.com/IotaTech-Info/IotaJava_G4/files/9783754/_JAVAG4_jiyi.pdf)

**Comment by CorasonZhang** [comment]
[事前テスト_JAVAG4_張伯陽.docx](https://github.com/IotaTech-Info/IotaJava_G4/files/9783935/_JAVAG4_.docx)

**Comment by wzz122** [comment]
[事前テスト_JAVAG4_呉壮壮.docx](https://github.com/IotaTech-Info/IotaJava_G4/files/9786450/_JAVAG4_.docx)

**Comment by 0131terre** [comment]
[事前テスト_JAVAG4_崔天蘊.docx](https://github.com/IotaTech-Info/IotaJava_G4/files/9788593/_JAVAG4_.docx)

**Comment by MercuryMicca** [comment]
研修サポート_関允

**Comment by Chank0229** [comment]
研修サポート_陳坤

**Comment by shibi1209** [comment]
研修サポート_徐紫薇

**Comment by Caden-wu** [comment]
研修サポート_呉龍
