### ISSUE TITLE
【サマリ】初期環境構築

### ISSUE THREAD

**Issue by IotaTech-Info** [IotaTech-Info/IotaJava_G4#2]
## ①　GITHUBのアカウント作成
https://github.com/

参考手順：https://qiita.com/ayatokura/items/9eabb7ae20752e6dc79d

## ②GIT token 作成
個人用トークン作成手順
Creating a personal access token
https://docs.github.com/cn/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

※作成済みのtokenに対して、必ず自宅PCで保存してください。

## ③リポジトリに招待
https://github.com/IotaTech-Info/IotaJava_G4/issues/3
⇒スケジュールのIssuseの下に、[自分名前のローマ字（姓_名）の形式]でコメントする
　例）ri_kinkan

※承認が必要のため、コメントしたら李まで連絡

## ④自分専用のbranch作成
★★★上記③の招待承認が必須★★★
https://github.com/IotaTech-Info/IotaJava_G4
[自分名前のローマ字（姓_名）の形式]でブランチを作成する
コピー先ブランチ名：mian

## ⑤Eclipseダウンロード
ツール
### ZOOM
https://zoom.us/download?_ga=2.96877661.339666053.1646099731-1260981934.1639207641#client_4meeting

### Eclipse
https://mergedoc.osdn.jp/
※windows , Macの区分があるため、自宅PCのOSよりダウンロードしてください。

## ⑥ローカル環境構築
手順：https://github.com/IotaTech-Info/IotaJava_G4

**Comment by IotaTech-Info** [comment]
テスト

**Comment by suponjiBOB** [comment]
ハンシエン

**Comment by xiaobao2024126** [comment]
HU-BAOTONG
