### ISSUE TITLE
スケジュール

### ISSUE THREAD

**Issue by IotaTech-Info** [IotaTech-Info/IotaJava_G4#3]
### 10/14まで
01 型＆式 - Java教育 - DCNet.pdf

### 10/21まで
02 型（文字列） - Java教育 - DCNet.pdf

### 10/28まで
03 フロー制御 - Java教育 - DCNet.pdf

### 11/4まで
04 配列 - Java教育 - DCNet.pdf
05 新米８問 - Java教育 - DCNet.pdf

### 12/09まで
06 関数 - Java教育 - DCNet.pdf
07 OOP - その１ - Java教育 - DCNet.pdf
08 OOP - その２ - Java教育 - DCNet.pdf
09 OOP - その３ - Java教育 - DCNet.pdf
07~09 OOP - 練習問題 - Java教育 - DCNet.pdf

### 12/23まで
10 文字列操作 - Java教育 - DCNet.pdf

### 2023/1/20まで
11 コレクション - Java教育 - DCNet.pdf
12 例外 - Java教育 - DCNet.pdf

### 2023/1/27まで
13 ファイルI_O - Java教育 - DCNet.pdf
14 日付 - Java教育 - DCNet.pdf

![image](https://user-images.githubusercontent.com/100652381/213441648-22e22692-b0ea-4538-866f-ba302ff85940.png)

**Comment by IotaTech-Info** [comment]
例）　ri_kinkan

**Comment by DYLism** [comment]
tai_gyokurin

**Comment by liuxiaoyang98** [comment]
Liu_Xiaoyang

**Comment by anastasia10c** [comment]
wangyiling_(:3 」∠)_

**Comment by xylh1116** [comment]
xue_yan

**Comment by SumizomeShizuku** [comment]
XU ZEKAI

**Comment by Hitsune369** [comment]
LI BIHENG

**Comment by Syunryou** [comment]
kaku_shunryo

**Comment by Knight-for-destiny** [comment]
song_zeyu

**Comment by hayleyqinn** [comment]
hong_qin

**Comment by SuperDolly** [comment]
Wu_Yuhang

**Comment by Yenyi03** [comment]
ui_yanyi

**Comment by daisylushadow** [comment]
lu_yuwen

**Comment by DYswag** [comment]
duan_zewei

**Comment by xulanxin** [comment]
xu_lanxin

**Comment by wzz122** [comment]
go_soso

**Comment by mazhiqiang26** [comment]
ma_zhiqiang

**Comment by CorasonZhang** [comment]
zhang_boyang

**Comment by JunyuChenJe** [comment]
chen_junyu

**Comment by 21q2106** [comment]
Li_rongrong

**Comment by see3rd** [comment]
xiong_wenqian

**Comment by 0131terre** [comment]
sai_tennun

**Comment by nakishigure** [comment]
chen_sihong

**Comment by chou-ikuyou** [comment]
chou-ikuyou

**Comment by donghe0216** [comment]
dong_he

**Comment by EB-Zengwenjie** [comment]
zeng_wenjie

**Comment by DDG-Edgerunners** [comment]
zhou_jingyang

**Comment by Haruka0204** [comment]
Wang_shaojun

**Comment by wangsy100** [comment]
wang_shuyu

**Comment by wangheng19941219** [comment]
wang_heng

**Comment by mazhiqiang26** [comment]
ma_zhiqiang

**Comment by TojoAnna** [comment]
Tojo_Anna

**Comment by kellymiaomiao** [comment]
wang_kaili

**Comment by maple1c** [comment]
luo_chang

**Comment by louyox** [comment]
xia_luyao

**Comment by jyiiki** [comment]
ji_yi

**Comment by smile19848400** [comment]
ye_yuhong

**Comment by jinlei0630** [comment]
jinlei
